PACKAGECONFIG ?= "zlib sxz"

PACKAGECONFIG[zlib] = "-DHDF5_ENABLE_ZLIB_SUPPORT=ON,-DHDF5_ENABLE_ZLIB_SUPPORT=OFF,zlib"
PACKAGECONFIG[sxz] = "-DHDF5_ENABLE_SZIP_SUPPORT=ON,-DHDF5_ENABLE_SZIP_SUPPORT=OFF,libaec"
